#! /bin/bash
#
# 

show_help () 
{
        # Show example usage
        echo -e "[vistalab/recon-all] 

        Example Usage: 
            docker run --rm -ti -v </input/dir/>:/input -v </output/dir/>:/output vistalab/recon-all -i /input/<input_file> -subjid <id> -all \n"
        # Prompt the user before displaying recon-all help
        echo "Would you like to see the DOC for recon-all? (y/N)"
        read response
        if [[ $response == "y" ]]
            then
                echo "Showing DOC for recon-all (type 'q' to exit):"
                sleep 2
                recon-all | less
            else
                echo "Goodbye."
        fi
}

# Check if the inputs are empty. 
# If so, show example usage and prompt for help
if [[ -z $@ ]]; then
    show_help
    exit
fi

# Run the algorithm 
recon-all $@ 

# Get a list of the folders in the output directory  
outputs=`find $SUBJECTS_DIR -mindepth 1 -maxdepth 2 -type d`

# If outputs exist, then go on...
if [[ -z $outputs ]] 
    then
        exit
    else
        echo "Compressing outputs..."

        # Set file permissions prior to compression
        chmod -R 777 $SUBJECTS_DIR/*

        # Compress the output to /tmp and name with current date and time
        zip -r /tmp/recon-all`date +"_D%m-%d-%yT%H-%M"`.zip $SUBJECTS_DIR/*
        
        # Remove the ucompressed output
        rm -rf $SUBJECTS_DIR/*

        # Move the results back and change the file permissions
        mv /tmp/recon-all*.zip $SUBJECTS_DIR
        chmod -R 777 $SUBJECTS_DIR
fi


