#! /bin/bash
#
# 

show_help () 
{
        # Show example usage
        echo -e "[vistalab/recon-all] 

        Example Usage: 
            docker run --rm -ti -v </input/dir/>:/input -v </output/dir/>:/output vistalab/recon-all -i /input/<input_file> -subjid <id> -all \n"
        # Prompt the user before displaying recon-all help
        echo "Would you like to see the DOC for recon-all? (y/N)"
        read response
        if [[ $response == "y" ]]
            then
                echo "Showing DOC for recon-all (type 'q' to exit):"
                sleep 2
                recon-all | less
            else
                echo "Goodbye."
                exit 0
        fi
}

# Check if the inputs are empty. 
# If so, show example usage and prompt for help
if [[ -z $@ ]]; then
    show_help
fi

# Run the algorithm 
recon-all $@ 

# Get a list of the folders in the output directory  
outputs=`find $SUBJECTS_DIR -mindepth 1 -maxdepth 2 -type d`

# If outputs exist, then go on...
if [[ -z $outputs ]] 
    then
        echo "Expected outputs were NOT found!"
        exit 1
    else
        echo "Compressing outputs..."

        # Set file permissions prior to compression
        chmod -R 777 $SUBJECTS_DIR/*

        # Compress the output to /tmp and name with current date and time
        results_dir=/recon-all_results_$4/
        mkdir $results_dir

        mv $SUBJECTS_DIR/* $results_dir
        zip -r /$SUBJECTS_DIR/recon-all_results_$4`date +"_D%m-%d-%yT%H-%M"`.zip $results_dir
        rm -rf $results_dir
        
        chmod -R 777 $SUBJECTS_DIR
fi

exit 0
